### ISSUE TITLE
query node with curl replied curl: (1) Received HTTP/0.9 when not allowed

### ISSUE THREAD

**Issue by NoFeeding** [kaspanet/kaspad#2212]
Hi I am new to this KASPA network and just setup a mainnet node.

But while I was trying query via this command
  curl --location --request GET 'http://127.0.0.1:16110/info/virtual-chain-blue-score'
when I am in local server or remotely with related IP address it all comes back with 
  curl: (1) Received HTTP/0.9 when not allowed

After I tried with --http0.9 parameter added it returned with 
  Warning: Binary output can mess up your terminal. Use "--output -" to tell 
  Warning: curl to output it to your terminal anyway, or consider "--output 
  Warning: <FILE>" to save to a file.
So I am wondering that if I missed out any essential setup besides setting listen=0.0.0.0:16111 and rpclisten=0.0.0.0:16110
Any more steps I need to take to curl some info from my node?

**Comment by MindPhaser34** [comment]
yep, same problem. Started with:
`kaspad --yes --nologfiles --disable-upnp --utxoindex --rpclisten=0.0.0.0:16110 --rpclisten-borsh=0.0.0.0:17110 --rpclisten-json=0.0.0.0:18110 --externalip=xxx.xxx.xxx.xxx`

**Comment by MindPhaser34** [comment]
Resolved with kaspa-api component in docker-compose:
```
  kaspa_rest_server:
    image: supertypo/kaspa-rest-server:latest
    container_name: kaspa-api
    hostname: kaspa-api
    restart: unless-stopped
    environment:
      KASPAD_HOST_1: kaspa-rusty-node:16110
      VSPC_REQUEST: "false"
    ports:
      - "8000:8000/tcp"
```

then you should do requests to kaspa-api.
